### ISSUE TITLE
[BUG] Add Device to CuPy cuFFT calls

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#184]
### Info
It looks like https://github.com/cupy/cupy/pull/3730 has changed the API in CuPy v8. That is breaking our tests.

```bash
self = <cusignal.test.test_convolution.TestConvolution.TestFFTConvolve object at 0x7f47d1e311f0>, rand_data_gen = <function rand_data_gen.<locals>._generate at 0x7f47ddf49430>, gpubenchmark = <rapids_pytest_benchmark.plugin.GPUBenchmarkFixture object at 0x7f47d1e31dc0>, num_samps = 32768, mode = 'valid'

    def test_fftconvolve_gpu(
        self, rand_data_gen, gpubenchmark, num_samps, mode
    ):
    
        cpu_sig, gpu_sig = rand_data_gen(num_samps)
>       output = gpubenchmark(
            cusignal.fftconvolve, gpu_sig, gpu_sig[::-1], mode=mode
        )

test/test_convolution.py:125: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/pytest_benchmark/fixture.py:127: in __call__
    return self._raw(function_to_benchmark, *args, **kwargs)
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/rapids_pytest_benchmark/plugin.py:262: in _raw
    function_result = super()._raw(function_to_benchmark, *args, **kwargs)
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/pytest_benchmark/fixture.py:173: in _raw
    function_result = function_to_benchmark(*args, **kwargs)
convolution/convolve.py:302: in fftconvolve
    sp1 = cp.fft.rfftn(in1, fshape, axes=axes)
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/cupy/fft/fft.py:793: in rfftn
    return func(a, s, axes, norm, cufft.CUFFT_FORWARD, 'R2C')
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/cupy/fft/fft.py:184: in _fft
    a = _exec_fft(a, direction, value_type, norm, axes[-1], overwrite_x)
../../../anaconda3/envs/cusignal-dev/lib/python3.8/site-packages/cupy/fft/fft.py:109: in _exec_fft
    plan = cufft.Plan1d(out_size, fft_type, batch, devices=devices)
cupy/cuda/cufft.pyx:263: in cupy.cuda.cufft.Plan1d.__init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   cupy.cuda.cufft.CuFFTError: CUFFT_INVALID_DEVICE

cupy/cuda/cufft.pyx:147: CuFFTError

```

**Comment by leofang** [comment]
All of the arguments needed to create a `Plan1d` should be filled in automatically, and users should not notice it. How was the CuPy v8 built? Which CUDA version?

**Comment by mnicely** [comment]
Let me ask the question, "How should I build it"?

If I want to use CUDA 11 as well. Or should I still be using CUDA 10.2

**Comment by leofang** [comment]
I think if built from the master branch, CUDA 11 support should be OK to use now, but be aware that C2R transforms are changed in CUDA 11 such that the input arrays will be destroyed (https://github.com/cupy/cupy/issues/3770). CUDA 10.x definitely works fine. 

I asked because I wasn't sure if you
1. cloned master, applied patch from cupy/cupy#3730, and tested, or
2. cloned my branch from from cupy/cupy#3730 directly, or
3. built CuPy in other means

Did you mean before the change in cupy/cupy#3730 it worked? Note that the `device` keyword-only argument was added long ago when the v8 development just started (cupy/cupy#2644), so likely things have been tested between then and now.

**Comment by mnicely** [comment]
Fixed by installing CuPy

```bash
pip install cupy-cuda102==8.0.0b5
```
