### ISSUE TITLE
[BUG] Installation Fails on Jetson Nano

### ISSUE THREAD

**Issue by gonesurfing** [rapidsai/cusignal#535]
**Describe the bug**
After installing on NVIDIA Jetson Nano, running pytest results in many failed results with "cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_FILE_NOT_FOUND: file not found". Appears to be similar to #217 

**Steps/Code to reproduce bug**
-Fresh install of Jetson Nano SD card
-Run apt update/upgrade
-Follow instructions on the README.md for cusignal instructions.
-Run "pytest" or run a script that uses channelize_poly.

**Expected behavior**
No errors when using library.

**Environment details (please complete the following information):**
 - Jetpack 461
 - Source method listed on README 

**Additional context**
-Maybe something broke when running update/upgrade?
(update)
Tried a fresh install with no apt upgrades, and similar result.
`263 failed, 1002 passed, 212 warnings in 495.72s (0:08:15)`
`FAILED cusignal/test/test_convolution.py::TestConvolution::TestCorrelate::test_correlate1d_gpu[direct-full-125-128] - cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_FILE_NOT_FOUND: file not found`

**Comment by awthomp** [comment]
Thanks for the bug report, @gonesurfing. We'll take a look!

**Comment by gonesurfing** [comment]
@awthomp Turns out it was just a PATH issue. I should have paid more attention to the "cannot find nvcc" messages during build.sh

pytest yields: 1265 passed, 213 warnings in 419.66s (0:06:59) 

Prior to cloning the condo environment and running build.sh, I issued the following:
$export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
$export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

Seems to be working now. Not sure if a good fix would be exiting the build script in a more verbose way if nvcc isn't found, or just updating the build instructions to ensure the environment variables are set.

Thanks,
Eric

**Comment by leofang** [comment]
More than often a cuSingal install issue is a CuPy install issue (which in turn is a `PATH`/`LD_LIBRARY_PATH` issue) 🙂 I think it might be better to suggest people to test `import cupy` first before `import cusignal` or even run `pytest`.

**Comment by awthomp** [comment]
Glad to see you got it resolved, Eric! Per Leo's suggestion, I'll suggest people `import cupy` first in the docs and file a PR today. Thanks again for using cuSignal and helping make it even better for others!
